# Generated by Django 4.2.3 on 2024-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=50)),
                ('TransactionID', models.CharField(max_length=255)),
                ('PaymentStatus', models.CharField(max_length=50)),
                ('DeliveredBy', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('DeliveredAt', models.DateTimeField(blank=True, null=True)),
                ('RestaurantID', models.IntegerField()),
            ],
        ),
    ]
