# Generated by Django 4.2.3 on 2024-01-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0002_paymenthistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='TransactionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
