# Generated by Django 4.2.3 on 2024-01-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0003_remove_paymenthistory_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
