# Generated by Django 3.2.4 on 2024-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0005_usermod_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(default=None, null=True)),
                ('address', models.CharField(max_length=255)),
                ('owner_id', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('rating', models.FloatField(null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('start_time', models.TimeField(default='00:00')),
                ('end_time', models.TimeField(default='23:59')),
            ],
        ),
    ]
