# Generated by Django 3.2.4 on 2024-01-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0006_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instant_item', models.BooleanField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField(default=None, null=True)),
                ('rating', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nosh.restaurant')),
            ],
        ),
    ]
