# Generated by Django 4.2.3 on 2024-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
