# Generated by Django 3.2.4 on 2024-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0009_alter_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instant_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
