# Generated by Django 3.2.4 on 2024-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0011_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PaymentType',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
