# Generated by Django 3.2.4 on 2024-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0012_order_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveredBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
