# Generated by Django 3.2.4 on 2024-01-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0013_alter_order_deliveredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='TransactionID',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
