# Generated by Django 3.2.4 on 2024-01-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0016_auto_20240126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='OrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nosh.order'),
        ),
    ]
