# Generated by Django 3.2.4 on 2024-01-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0017_alter_paymenthistory_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nosh.restaurant'),
        ),
    ]
