# Generated by Django 4.2.3 on 2024-01-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0018_alter_order_restaurantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='RestaurantID',
        ),
    ]
