# Generated by Django 4.2.3 on 2024-01-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0019_remove_order_restaurantid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='RestaurantID',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='nosh.restaurant'),
            preserve_default=False,
        ),
    ]
