# Generated by Django 3.2.4 on 2024-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0020_order_restaurantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='Reason',
            field=models.CharField(choices=[('order_cancellation', 'Order Cancellation'), ('order_place', 'Order Place')], max_length=50),
        ),
    ]
