# Generated by Django 3.2.4 on 2024-01-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosh', '0023_auto_20240128_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='OTP',
            field=models.CharField(max_length=64),
        ),
    ]
